[{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-selectorexpected",
	"severity": 8,
	"message": "Cần bộ chọn",
	"source": "css",
	"startLineNumber": 1,
	"startColumn": 15,
	"endLineNumber": 1,
	"endColumn": 16,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 1,
	"startColumn": 37,
	"endLineNumber": 1,
	"endColumn": 38,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 1,
	"startColumn": 44,
	"endLineNumber": 1,
	"endColumn": 51,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 3,
	"startColumn": 13,
	"endLineNumber": 3,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lbracketexpected",
	"severity": 8,
	"message": "Thiếu ký tự ]",
	"source": "css",
	"startLineNumber": 5,
	"startColumn": 20,
	"endLineNumber": 5,
	"endColumn": 21,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 5,
	"startColumn": 35,
	"endLineNumber": 5,
	"endColumn": 36,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 7,
	"startColumn": 3,
	"endLineNumber": 7,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 8,
	"startColumn": 12,
	"endLineNumber": 8,
	"endColumn": 13,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 11,
	"startColumn": 5,
	"endLineNumber": 11,
	"endColumn": 6,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-colonexpected",
	"severity": 8,
	"message": "Thiếu dấu hai chấm",
	"source": "css",
	"startLineNumber": 12,
	"startColumn": 15,
	"endLineNumber": 12,
	"endColumn": 16,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 14,
	"startColumn": 3,
	"endLineNumber": 14,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 14,
	"startColumn": 18,
	"endLineNumber": 14,
	"endColumn": 19,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 16,
	"startColumn": 21,
	"endLineNumber": 16,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 18,
	"startColumn": 18,
	"endLineNumber": 18,
	"endColumn": 19,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 19,
	"startColumn": 3,
	"endLineNumber": 19,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 21,
	"startColumn": 10,
	"endLineNumber": 21,
	"endColumn": 11,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 23,
	"startColumn": 140,
	"endLineNumber": 23,
	"endColumn": 141,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 26,
	"startColumn": 21,
	"endLineNumber": 26,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 29,
	"startColumn": 20,
	"endLineNumber": 29,
	"endColumn": 21,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 32,
	"startColumn": 9,
	"endLineNumber": 32,
	"endColumn": 10,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 33,
	"startColumn": 7,
	"endLineNumber": 33,
	"endColumn": 8,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 36,
	"startColumn": 7,
	"endLineNumber": 36,
	"endColumn": 8,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 36,
	"startColumn": 20,
	"endLineNumber": 36,
	"endColumn": 21,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 42,
	"startColumn": 49,
	"endLineNumber": 42,
	"endColumn": 50,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 77,
	"startColumn": 24,
	"endLineNumber": 77,
	"endColumn": 25,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 85,
	"startColumn": 13,
	"endLineNumber": 85,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 85,
	"startColumn": 27,
	"endLineNumber": 85,
	"endColumn": 28,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 93,
	"startColumn": 13,
	"endLineNumber": 93,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 93,
	"startColumn": 27,
	"endLineNumber": 93,
	"endColumn": 28,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 99,
	"startColumn": 13,
	"endLineNumber": 99,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 99,
	"startColumn": 27,
	"endLineNumber": 99,
	"endColumn": 28,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 106,
	"startColumn": 5,
	"endLineNumber": 106,
	"endColumn": 6,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 107,
	"startColumn": 3,
	"endLineNumber": 107,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "Thiếu quy tắc @ hoặc bộ chọn",
	"source": "css",
	"startLineNumber": 108,
	"startColumn": 1,
	"endLineNumber": 108,
	"endColumn": 2,
	"modelVersionId": 4,
	"origin": "extHost2"
},{
	"resource": "/workspaces/gizmo-pro/src/App.css",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "Cần {.",
	"source": "css",
	"startLineNumber": 110,
	"startColumn": 19,
	"endLineNumber": 110,
	"endColumn": 20,
	"modelVersionId": 4,
	"origin": "extHost2"
}]

export default App;